# Generated by Django 5.2 on 2025-04-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_email_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='account_locked',
            field=models.BooleanField(default=False),
        ),
    ]
