# Generated by Django 5.2 on 2025-05-28 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customuser_account_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='currency',
            field=models.CharField(choices=[('COP', 'Peso Colombiano'), ('USD', 'Dólar Estadounidense'), ('EUR', 'Euro')], default='COP', max_length=5),
        ),
        migrations.AddField(
            model_name='customuser',
            name='language',
            field=models.CharField(choices=[('es', 'Español'), ('en', 'English')], default='es', max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='meal_preference',
            field=models.CharField(blank=True, choices=[('standard', 'Estándar'), ('vegetarian', 'Vegetariano'), ('vegan', 'Vegano')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_photo',
            field=models.URLField(blank=True, null=True, verbose_name='Foto de perfil (URL)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='seat_preference',
            field=models.CharField(blank=True, choices=[('window', 'Ventana'), ('aisle', 'Pasillo'), ('none', 'Sin preferencia')], default='none', max_length=20),
        ),
    ]
