# Generated by Django 5.2 on 2025-05-13 23:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_alter_booking_booking_date_alter_booking_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de pago')),
                ('transaction_id', models.CharField(max_length=100, unique=True, verbose_name='ID de transacción')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallido'), ('REFUNDED', 'Reembolsado')], default='PENDING', max_length=10, verbose_name='Estado')),
                ('payment_method', models.CharField(choices=[('QR', 'Pago con QR'), ('CARD', 'Tarjeta de crédito'), ('CASH', 'Efectivo'), ('TRANSFER', 'Transferencia bancaria')], default='QR', max_length=10, verbose_name='Método de pago')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='payments/qr/', verbose_name='Código QR')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=4, verbose_name='Número de asiento')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('RESERVED', 'Reservado'), ('OCCUPIED', 'Ocupado')], default='AVAILABLE', max_length=10, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Asiento',
                'verbose_name_plural': 'Asientos',
            },
        ),
        migrations.AlterModelOptions(
            name='airline',
            options={'verbose_name': 'Aerolínea', 'verbose_name_plural': 'Aerolíneas'},
        ),
        migrations.AlterModelOptions(
            name='airport',
            options={'ordering': ['city'], 'verbose_name': 'Aeropuerto', 'verbose_name_plural': 'Aeropuertos'},
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-booking_date'], 'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.AlterModelOptions(
            name='flight',
            options={'ordering': ['departure_time'], 'verbose_name': 'Vuelo', 'verbose_name_plural': 'Vuelos'},
        ),
        migrations.AddField(
            model_name='airport',
            name='timezone',
            field=models.CharField(default='UTC', help_text='Ejemplo: America/Bogota', max_length=50, verbose_name='Zona Horaria'),
        ),
        migrations.AddField(
            model_name='flight',
            name='total_seats',
            field=models.PositiveIntegerField(default=180, verbose_name='Total de asientos'),
        ),
        migrations.AlterField(
            model_name='airline',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='airlines/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='airline',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='code',
            field=models.CharField(max_length=3, unique=True, verbose_name='Código IATA'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='country',
            field=models.CharField(max_length=100, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre del aeropuerto'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de reserva'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_reference',
            field=models.CharField(max_length=8, unique=True, verbose_name='Referencia de reserva'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.flight', verbose_name='Vuelo'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='passengers',
            field=models.IntegerField(default=1, verbose_name='Número de pasajeros'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('SELECTED', 'Seleccionado'), ('PENDING', 'Pendiente de pago'), ('CONFIRMED', 'Confirmado'), ('CANCELLED', 'Cancelado')], db_index=True, default='SELECTED', max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio total'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='airline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.airline', verbose_name='Aerolínea'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='flights.airport', verbose_name='Aeropuerto de llegada'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_time',
            field=models.DateTimeField(verbose_name='Hora de llegada'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='available_seats',
            field=models.PositiveIntegerField(verbose_name='Asientos disponibles'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='flights.airport', verbose_name='Aeropuerto de salida'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_time',
            field=models.DateTimeField(verbose_name='Hora de salida'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_number',
            field=models.CharField(max_length=10, unique=True, verbose_name='Número de vuelo'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica si el vuelo está disponible para reservas', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Precio en pesos colombianos', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio (COP)'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['departure_time'], name='flights_fli_departu_5bc2af_idx'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['is_active'], name='flights_fli_is_acti_2185d0_idx'),
        ),
        migrations.AddField(
            model_name='payment',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='flights.booking', verbose_name='Reserva'),
        ),
        migrations.AddField(
            model_name='seat',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_seats', to='flights.booking', verbose_name='Reserva asociada'),
        ),
        migrations.AddField(
            model_name='seat',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='flights.flight', verbose_name='Vuelo'),
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('flight', 'seat_number')},
        ),
    ]
