# Generated by Django 5.2 on 2025-05-14 00:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_payment_seat_alter_airline_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'status'], name='flights_boo_user_id_72f7c9_idx'),
        ),
        migrations.AddIndex(
            model_name='seat',
            index=models.Index(fields=['flight', 'status'], name='flights_sea_flight__760cb4_idx'),
        ),
        migrations.AddIndex(
            model_name='seat',
            index=models.Index(fields=['booking'], name='flights_sea_booking_cc117a_idx'),
        ),
    ]
