# Generated by Django 5.2 on 2025-05-26 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_booking_flights_boo_user_id_72f7c9_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='lat',
            field=models.FloatField(default=0.0, verbose_name='Latitud'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airport',
            name='lng',
            field=models.FloatField(default=0.0, verbose_name='Longitud'),
            preserve_default=False,
        ),
    ]
